added rubocop and started fixed rubocop warnings.
Fixed rubocop warnings.

Fixed rubocop warnings.

Fixed rubocop warnings.
Added options for ignoring internal and external links.

Added better logging for verbose output.

Fixed JRUBY error.

Fixed JRUBY "NameError: uninitialized constant Blinker::ManticoreWrapper::HttpUtils" error.

Added default_external encoding

Blinkr was not checking both internal and external links.

Blinkr was not checking both internal and external links.

Cherry picked Jason's JRuby Fixes, added ignore internal/external flags, fixed more robocop errors.

Fixed issue with JRuby.

Added default report location to be saved and better output when link checking is complete.

remove ssl errors in staging.

removed ssl errors hack.

Added fix for forbidden redirects http -> https
added flag to ignore ssl checks

Updated flag to ignore ssl checks

Updated user-agent string.

Added debug puts

Moved ignore internal/external link methods

Attempting to fix ignore internal/external links

fixed issue with checking single URL.

Fixed issues with ignoring internal/external links.

Possible fix for ignoring internal urls.

yet another fix for ignoring internal/external urls.

updated gemfile dependencies

Fixed issue with generating reports.

Upped wait time on page load.

possible fix for caching issues.

Fixing "bundler: failed to load command: blinkr (/usr/local/bundle/bin/blinkr)
        NoMethodError: undefined method `[]' for nil:NilClass" error when checking both internal and external url's

Fixing "bundler: failed to load command: blinkr (/usr/local/bundle/bin/blinkr)
        NoMethodError: undefined method `[]' for nil:NilClass" error when checking both internal and external url's

added example code for raising an error when a link is poiting to an incorrect environment.

added example code for raising an error when a link is poiting to an incorrect environment.

added debug puts

removed debug puts

removed debug puts

Fixed issue with parsing config file.

reformatted code.

Refactored links extension.
Made minor changes to console output.

possible fix for relative links. Only a debug puts at the moment. If this works on PR then will proceed with the fix.

possible fix for relative links.

added debug puts

added debug puts

added optional warnings for javascript, css, and missing from sitemap.

added optional warnings for javascript, css, and missing from sitemap.

Fixing issue with sitemap warnings.

added puts for debugging

added puts for debugging

added puts for debugging

fixed typo

fixed issue with sitemap warnings.

fixed issue with sitemap warnings.

if already warned that missing from sitemap, don't raise again

added debug puts

added debug puts

moved already warned

moved already warned

moved already warned

Tidy up.

Don't warn resource errors by default.

fixed issue with Blinkr report not rendering correctly on Jenkins.

Initial commit of unit-tests.

Initial commit of unit-tests and some bug-fixes.

Config file was not being read correctly and options were being ignored <- Fixed
Updated unit-tests to reflect config fix.

Fixed broken unit-test